# To "make"       run in terminal: "make client" or "make server"
# To "make clean" run in terminal: "make client_clean" or "make server_clean"
sub:
	make -f makefile.sub
sub_clean:
	make clean -f makefile.sub
pub:
	make -f makefile.pub
pub_clean:
	make clean -f makefile.pub
ssdpController:
	make -f makefile.ssdpController
ssdpController_clean:
	make clean -f makefile.ssdpController
mqttController:
	make -f makefile.mqttController
mqttController_clean:
	make clean -f makefile.mqttController
