IDIR =../inc
CC=g++
CFLAGS=-ggdb -I$(IDIR) -Wall -lpthread

ODIR=../obj
LDIR =../lib

LIBS=-lm

_DEPS = messageParser.h jsonParser.h json.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = controller.o messageParser.o jsonParser.o jsoncpp.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

controller: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f controller $(ODIR)/*.o *~ core $(INCDIR)/*~ 
